### ISSUE TITLE
Question about r + δr, s + δs 

### ISSUE THREAD

**Issue by wzy-99** [ingra14m/Deformable-3D-Gaussians#10]
There two methods to realize r + δr, s + δs 

1. base value addition

```py
self._scaling + delt
```

as: https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/gaussian_model.py#L50C19-L50C19

2. activated value addition

```py
self.opacity_activation(self._opacity) + delt
```

as: https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/gaussian_model.py#L115

which one you take?

**Comment by wzy-99** [comment]
Tnanks for your answer

**Comment by Agent-INF** [comment]
Hey @ingra14m 
I find that your code seems to implement the latter. Is this a mistake or is it intentional?
(https://github.com/ingra14m/Deformable-3D-Gaussians/blob/152ff1fff21abff0400bfa6df9cc9ee50c9b9694/gaussian_renderer/__init__.py#L87C16-L87C16)
```
        scales = pc.get_scaling + d_scaling
        rotations = pc.get_rotation + d_rotation
```
where `get_scaling `and `get_rotation` are both activated value: (https://github.com/ingra14m/Deformable-3D-Gaussians/blob/152ff1fff21abff0400bfa6df9cc9ee50c9b9694/scene/gaussian_model.py#L58C6-L58C6)
```
    @property
    def get_scaling(self):
        return self.scaling_activation(self._scaling)

    @property
    def get_rotation(self):
        return self.rotation_activation(self._rotation)
```
Should this part of the code be modified like this:
```
        scales = pc.scaling_activation(pc._scaling + d_scaling)
        rotations = pc.rotation_activation(pc._rotation + d_rotation)
```

**Comment by ingra14m** [comment]
Hi, sorry for late reply. Because I cannot receive messages in time for issues that are closed. 

Your modification is certainly physically correct, and this change is very appropriate. However, in early attempts, this would reduce the rendering quality. Therefore, I adopted the format in the code, which is kind of a trick for quality.
