### ISSUE TITLE
my_dataset

### ISSUE THREAD

**Issue by Tiandishihua** [ingra14m/Deformable-3D-Gaussians#4]
Can I use my own video data?

**Comment by ingra14m** [comment]
Hi, thank you for your interest for this work. You can certainly use the videos you've captured. This method only requires images and their corresponding poses. 

For monocular videos, the accuracy of pose estimation is crucial. HyperNeRF uses colmap to estimate the pose for each frame, but there is a significant amount of error in this process, which is not favorable for the convergence of Deformable-Gaussian. If you have a better method for estimating pose in monocular videos, that would be excellent. 

Regarding multi-view videos, Deformable-Gaussian can handle them, since a method that works for monocular videos can certainly be applied to multi-view scenarios. However, I believe that compared to extracting features from other views of the same frame and then reprojecting them to the current view, as in methods like [im4d](https://github.com/zju3dv/im4d), our approach doesn't offer a significant advantage.
