### ISSUE TITLE
questions about the deformation field

### ISSUE THREAD

**Issue by cv-lab-x** [ingra14m/Deformable-3D-Gaussians#6]
hi, thanks for your great work, some questions about the deformation field, as you mentioned in your paper,  "The deformation field takes the positions of the 3D Gaussians and the current time t as inputs, outputting δx, δr, and δs.", why you optimize the deformation field just input the **position (xyz)** in 3D gaussion, but output **δx, δr, and δs**?  how this work in your pipeline or make sense? @ingra14m

**Comment by ingra14m** [comment]
Hi, thanks for your interest in our work.

Regarding the output. According to the Equ. 3 and 5 in the [3D-GS paper](https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/), there are two processes to go from 3D-GS to a rendered image: 
1. Determine the position of 3D-GS in the 2D rendered image through rotation and scaling (Equ. 5). 
2. Integrate volume rendering according to Equ. 3 to get the color of each pixel. 

Therefore, the parameters affecting the contribution of 3D-GS to the rendered image are only position, rotation, and scaling. Consequently, these are also the parameters that need to be deformed when 3D-GS models dynamic scenes.

Regarding the input, to be honest, it is more like the optimal solution obtained from experiments. Whether only inputting the position, or inputting all three (position, rotation, scaling), both can be reasonably explained. Inputting only the position has a clear rationale in that it confines the factors affecting motion to the 3D space, rather than 2D rendering space. 

However, no matter which input method is used, fitting the motion is extremely complicated, because in the early stages of training, the 3D-GS position inputted each time is different. This is not like D-NeRF/HyperNeRF, where each sample point is constant in the canonical space. This is also why I did not adopt the Plane/Grid-Based method, and instead directly used MLP to model the deformation field, because Plane/Grid-Based methods are based on a **low-rank assumption**. Dynamic scenes have complex topological changes, and the continuously changing 3D-GS position during training further increases the rank of the scene. 

Based on the method of inputting only the position, by around 300k, the position of the canonical 3D-GS has already converged and become constant.
